export const LIST_FILES_DEFAULT_LIMIT = 500
export const LIST_FILES_MAX_LIMIT = 500

export const SEARCH_CODE_DEFAULT_LIMIT = 100
export const SEARCH_CODE_MAX_LIMIT = 100

export const FILESYSTEM_OUTPUT_MAX_LINES = 2_000
export const FILESYSTEM_OUTPUT_MAX_BYTES = 50 * 1_024
